services:
  - type: web
    name: chihiro-note
    env: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start
    previews:
      generation: automatic
    envVars:
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
