ALTER TABLE settings ADD COLUMN IF NOT EXISTS tab_diary TEXT NOT NULL DEFAULT '日記';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS tab_notes TEXT NOT NULL DEFAULT 'ノート';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS tab_todo TEXT NOT NULL DEFAULT 'TO-DO';
